# Generated by Django 4.2.2 on 2023-07-31 07:39

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('ltpl', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='All_Departments',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('department_name', models.CharField(max_length=50)),
            ],
            options={
                'db_table': 'all_departments',
            },
        ),
        migrations.RemoveField(
            model_name='employee',
            name='id',
        ),
        migrations.AddField(
            model_name='employee',
            name='gender',
            field=models.CharField(choices=[('Select', '--- Select Gender ---'), ('Male', 'Male'), ('Female', 'Female'), ('Other', 'Other')], default='Select'),
        ),
        migrations.AlterField(
            model_name='employee',
            name='username',
            field=models.CharField(max_length=12, primary_key=True, serialize=False),
        ),
        migrations.CreateModel(
            name='Department',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('employees', models.ManyToManyField(related_name='departments', to='ltpl.employee')),
                ('name', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='departments', to='ltpl.all_departments')),
            ],
            options={
                'db_table': 'department',
            },
        ),
        migrations.CreateModel(
            name='Address',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('street', models.CharField(max_length=100)),
                ('city', models.CharField(max_length=50)),
                ('state', models.CharField(max_length=50)),
                ('zipcode', models.CharField(max_length=10)),
                ('employee', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='address', to='ltpl.employee')),
            ],
            options={
                'db_table': 'address',
            },
        ),
    ]
